# Generated by Django 3.0.2 on 2020-01-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_books', '0002_auto_20200106_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='checked_by',
            field=models.CharField(default='', max_length=254),
        ),
    ]
