# Generated by Django 3.0.2 on 2020-01-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_books', '0003_book_checked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='checked_by',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
